// import './globals.css'
import Navbar from '@/components/Navbar'
import Contact from '@/components/Contact'
import "./globals.scss"

export const metadata = {
  title: 'My Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        <header>
          <Navbar />
        </header>
        {children}
        <footer>
          <Contact />
        </footer>
      </body>
    </html>
  )
}
